apiVersion: apps/v1
kind: Deployment
metadata:
  name: hyperhive-api-gateway
  namespace: hyperhive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api_gateway
  template:
    metadata:
     labels:
       app: api_gateway
    spec:
      containers:
        - name: apigateway-container
          image: {{ .Values.apigateway.image }}{{ .Values.apigateway.tag }}
          ports:
            - containerPort: 8000
          resources:
            limits:
              memory: {{ .Values.resources.limits.memory | default "201Mi"}}
              cpu: {{ .Values.resources.limits.cpu | default "0.3"}}
            requests:
              memory: 150Mi
              cpu: "0.1"


---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: hyperhive
spec:
  type: NodePort
  ports:
    - targetPort: 8000
      port: 8000
      nodePort: 30003
  selector: 
    app: api_gateway

