apiVersion: apps/v1
kind: Deployment
metadata:
  name: hyperhive-api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api_gateway
  template:
    metadata:
     labels:
       app: api_gateway
    spec:
      containers:
        - name: api-gateway-container
          image: vajidhussain/hyperhive_api_gateway
          ports:
            - containerPort: 8000
          resources:
            limits:
              memory: 212Mi
              cpu: "1"
            requests:
              memory: 150Mi
              cpu: "0.2"



---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  type: NodePort
  ports:
    - targetPort: 8000
      port: 8000
      nodePort: 30003
  selector: 
    app: api_gateway

