apiVersion: apps/v1
kind: Deployment
metadata:
  name: hyperhive-auth-svc
  NameSpace: hyperhive
spec:
  selector:
    matchLabels:
      app: auth_service
  template:
    metadata:
      labels:
        app: auth_service
    spec:
      containers:
        - image: vajidhussain/hyperhive_auth_service
          name: auth-svc-container
          ports:
            - containerPort: 8001
          resources:
            limits:
              memory: 212Mi
              cpu: "1"
            requests:
              memory: 150Mi
              cpu: "0.2"


---
apiVersion: v1
kind: Service
metadata:
  name: auth-services
  NameSpace: hyperhive
spec: 
  type: ClusterIP
  ports:
    - port: 8001
      targetPort: 8001
  selector:
    app: auth_service
    