apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hyperhive-certificate
  namespace: hyperhive
spec:
  dnsNames:
    - k8s.hyperhive.vajid.tech
  secretName: hyperhive-new-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
