apiVersion: apps/v1
kind: Deployment
metadata:
  name: hyperhive-friend-svc
  namespace: hyperhive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: friend_service
  template:
    metadata:
      labels: 
        app: friend_service
    spec:
      containers:
      - image: vajidhussain/hyperhive_friend_service
        name: friend-svc-container
        ports:
        - containerPort: 8002
        resources:
          limits:
            cpu: ".2"
            memory: "250Mi"
          requests:
            cpu: ".1"
            memory: "150Mi"
        

---

apiVersion: v1
kind: Service
metadata:
  namespace: hyperhive
  name: friend-service
spec:
  type: ClusterIP
  ports:
  - port: 8002
    targetPort: 8002
  selector:
    app: friend_service