apiVersion: apps/v1
kind: Deployment
metadata:
  name: hyperhive-server-svc
  namespace: hyperhive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server_service
  template:
    metadata:
      labels:
        app: server_service
    spec:
      containers:
        - name: server-svc-container
          image: vajidhussain/hyperhive_server_service
          ports:
          -  containerPort: 8003
          resources:
            limits:
              memory: 212Mi
              cpu: ".2"
            requests:
              memory: 150Mi
              cpu: "0.1"

---

apiVersion: v1
kind: Service
metadata:
  name: server-service
  namespace: hyperhive
spec: 
  type: ClusterIP
  ports:
    - port: 8003
      targetPort: 8003
  selector:
    app: server_service
