name: api-gateway
run-name: ${{ github.actor }} is deploying api-gateway
on: 
  push:
    # paths:
    # - '/api-gateway/'
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    - name: List Files
      run: ls
    - name: pwd
      run: pwd
    # - name: cd
    #   run: cd 
    - name: print secret
      run: echo "done ${{ secrets.DOCKER_USERNAME }}" 
    - name: Checkout
      uses: actions/checkout@v4
    - name: Login to docker hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: setup docker buildx
      uses: docker/setup-buildx-action@v3
    - name: build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: /api-gateway/dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/hyperhive_api_gateway:latest
